name: Generate and Deploy Documentation on GitHub Pages

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.2

            - name: Install dependencies
              run: composer install

            - name: Download phpDocumentor PHAR
              run: wget https://phpdoc.org/phpDocumentor.phar

            - name: Make phpDocumentor executable
              run: chmod +x phpDocumentor.phar

            - name: Generate Documentation
              run: phpdocumentor.phar -d ./src,./tests -t docs

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
